/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LibraryImport } from './routes/library'
import { Route as IndexImport } from './routes/index'
import { Route as RandomIndexImport } from './routes/random.index'
import { Route as RandomMemeIdImport } from './routes/random.$memeId'

// Create/Update Routes

const LibraryRoute = LibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RandomIndexRoute = RandomIndexImport.update({
  id: '/random/',
  path: '/random/',
  getParentRoute: () => rootRoute,
} as any)

const RandomMemeIdRoute = RandomMemeIdImport.update({
  id: '/random/$memeId',
  path: '/random/$memeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryImport
      parentRoute: typeof rootRoute
    }
    '/random/$memeId': {
      id: '/random/$memeId'
      path: '/random/$memeId'
      fullPath: '/random/$memeId'
      preLoaderRoute: typeof RandomMemeIdImport
      parentRoute: typeof rootRoute
    }
    '/random/': {
      id: '/random/'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/random/$memeId': typeof RandomMemeIdRoute
  '/random': typeof RandomIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/random/$memeId': typeof RandomMemeIdRoute
  '/random': typeof RandomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/random/$memeId': typeof RandomMemeIdRoute
  '/random/': typeof RandomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/random/$memeId' | '/random'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/random/$memeId' | '/random'
  id: '__root__' | '/' | '/library' | '/random/$memeId' | '/random/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  RandomMemeIdRoute: typeof RandomMemeIdRoute
  RandomIndexRoute: typeof RandomIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  RandomMemeIdRoute: RandomMemeIdRoute,
  RandomIndexRoute: RandomIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/library",
        "/random/$memeId",
        "/random/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/library": {
      "filePath": "library.tsx"
    },
    "/random/$memeId": {
      "filePath": "random.$memeId.tsx"
    },
    "/random/": {
      "filePath": "random.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
