/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as PublicImport } from './routes/_public'
import { Route as PublicIndexImport } from './routes/_public.index'
import { Route as DashboardLibraryImport } from './routes/dashboard.library'
import { Route as PublicPricingImport } from './routes/_public.pricing'
import { Route as DashboardRandomIndexImport } from './routes/dashboard.random.index'
import { Route as DashboardRandomMemeIdImport } from './routes/dashboard.random.$memeId'

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const DashboardLibraryRoute = DashboardLibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)

const PublicPricingRoute = PublicPricingImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRoute,
} as any)

const DashboardRandomIndexRoute = DashboardRandomIndexImport.update({
  id: '/random/',
  path: '/random/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardRandomMemeIdRoute = DashboardRandomMemeIdImport.update({
  id: '/random/$memeId',
  path: '/random/$memeId',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingImport
      parentRoute: typeof PublicImport
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryImport
      parentRoute: typeof DashboardImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/dashboard/random/$memeId': {
      id: '/dashboard/random/$memeId'
      path: '/random/$memeId'
      fullPath: '/dashboard/random/$memeId'
      preLoaderRoute: typeof DashboardRandomMemeIdImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/random/': {
      id: '/dashboard/random/'
      path: '/random'
      fullPath: '/dashboard/random'
      preLoaderRoute: typeof DashboardRandomIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface PublicRouteChildren {
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardRouteChildren {
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardRandomMemeIdRoute: typeof DashboardRandomMemeIdRoute
  DashboardRandomIndexRoute: typeof DashboardRandomIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardRandomMemeIdRoute: DashboardRandomMemeIdRoute,
  DashboardRandomIndexRoute: DashboardRandomIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PublicPricingRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/': typeof PublicIndexRoute
  '/dashboard/random/$memeId': typeof DashboardRandomMemeIdRoute
  '/dashboard/random': typeof DashboardRandomIndexRoute
}

export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PublicPricingRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/': typeof PublicIndexRoute
  '/dashboard/random/$memeId': typeof DashboardRandomMemeIdRoute
  '/dashboard/random': typeof DashboardRandomIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/pricing': typeof PublicPricingRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/random/$memeId': typeof DashboardRandomMemeIdRoute
  '/dashboard/random/': typeof DashboardRandomIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/dashboard'
    | '/pricing'
    | '/dashboard/library'
    | '/'
    | '/dashboard/random/$memeId'
    | '/dashboard/random'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/pricing'
    | '/dashboard/library'
    | '/'
    | '/dashboard/random/$memeId'
    | '/dashboard/random'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/_public/pricing'
    | '/dashboard/library'
    | '/_public/'
    | '/dashboard/random/$memeId'
    | '/dashboard/random/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_public",
        "/dashboard"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/pricing",
        "/_public/"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/library",
        "/dashboard/random/$memeId",
        "/dashboard/random/"
      ]
    },
    "/_public/pricing": {
      "filePath": "_public.pricing.tsx",
      "parent": "/_public"
    },
    "/dashboard/library": {
      "filePath": "dashboard.library.tsx",
      "parent": "/dashboard"
    },
    "/_public/": {
      "filePath": "_public.index.tsx",
      "parent": "/_public"
    },
    "/dashboard/random/$memeId": {
      "filePath": "dashboard.random.$memeId.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/random/": {
      "filePath": "dashboard.random.index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
